### ISSUE TITLE
Need prefix for class name 'Component'

### ISSUE THREAD

**Issue by hilalbaig** [bazrafkan/google_place#1]
**Problem:**
There is conflict of **google_places** package with **google_maps_webservice**

The name 'Component' is defined in the libraries '**package:google_maps_webservice/src/core.dart** (via **package:google_maps_webservice/places.dart**)' and '**package:google_place/src/models/component.dart** (via **package:google_place/google_place.dart**)'.

**Solution:**
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.dart(ambiguous_import)
'Component' isn't a function.

Try correcting the name to match an existing function, or define a method or function named 'Component'.dart(invocation_of_non_function)

**Comment by hilalbaig** [comment]
Just solved to avoid the conflict, by doing:

import 'package:google_place/google_place.dart' **hide Component**;

**Comment by bazrafkan** [comment]
Hello
Tanks for your issues.
You can set prefix for this package like this:

```dart
import 'package:google_place/google_place.dart' as googlePlace;
var gPlace = googlePlace.GooglePlace("Your-Key");
var risult = await gPlace.autocomplete.get("1600 Amphitheatre");
```
