### ISSUE TITLE
Search as you type alternating between REQUEST_DENIED and results

### ISSUE THREAD

**Issue by lukepighetti** [bazrafkan/google_place#13]
When using material search API in flutter to trigger search-as-you-type in a naiive fashion I get results mixed in with request denied errors.

```
    final result =
        await _googlePlace.autocomplete.get(query, types: '(cities)');

    /// Request denied
    if (result.status == 'REQUEST_DENIED') {
      print('Google Places API – Request Denied');
    } else if (result.status == 'ZERO_RESULTS') {
      print('Google Places API - No results found');
    } else {
      print(result.status);
    }
```

```
flutter: [h, [ChIJgTWgBRs1rkwRpHpP5mHeDJc, ChIJk2tNWqFJrkwRLyiJao0SSbo, ChIJAYWNSLS4QIYROwVl894CDco, ChIJofaJZoZSrkwRLY4oKAw6V4o, ChIJpVER8hFT5okRmVl96ahKjsw]]
flutter: [he, [ChIJgTWgBRs1rkwRpHpP5mHeDJc, ChIJk2tNWqFJrkwRLyiJao0SSbo, ChIJAYWNSLS4QIYROwVl894CDco, ChIJofaJZoZSrkwRLY4oKAw6V4o, ChIJpVER8hFT5okRmVl96ahKjsw]]
flutter: Google Places API – Request Denied
flutter: [he, []]
flutter: [hel, []]
flutter: [hell, []]
flutter: Google Places API – Request Denied
flutter: Google Places API – Request Denied
flutter: [hell, []]
flutter: [hello, []]
flutter: OK
flutter: [hello, [ChIJzfk9mlyLxkcR0deR5IaJFas, ChIJLWJrgnRsXIYRFXB0qq8GOF0, ChIJb-ZAjaIH4UcR-wJLDIpOc60, ChIJs8oMpZFu30cRbybbXERthVs, ChIJAReKwtIK4kcRHDn-t0AKvMg]]
```

**Comment by bazrafkan** [comment]
I'll check, thanks.

**Comment by nehal076** [comment]
I'm facing the same issue.

**Comment by lukepighetti** [comment]
I'm not involved in this project anymore, but I suspect it could have been resolved with throttling the keystrokes

**Comment by nehal076** [comment]
But I am only getting this status REQUEST_DENIED, and nothing else.

**Comment by vuln3r** [comment]
I'm facing the same issue here... I see requests in the console but all of them with the status `REQUEST_DENIED`

**Comment by Dreezyagu** [comment]
I'm facing the same issue. I have enabled all the required APIs in the Cloud Console

**Comment by fleeser** [comment]
@bazrafkan Any idea on when to fix this?

**Comment by fleeser** [comment]
@lukepighetti I ran into the exact same problem at first, but after a while it got tsuck with only the REQUEST_DENIED status.
Now, I tried to fetch data by manually making HTTP requests and found out that the status REQUEST_DENIED is not only send to the client when using wrong API keys, but also when Billing is not activated for the project. Here is what I got sent: 

**You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable**

Maybe this helps some of you guys.

**Comment by Dreezyagu** [comment]
Make sure you enable Billing on the Google Cloud platform. You will be required to provide your card details, pictures of the card and an ID.

**Comment by vuln3r** [comment]
> @lukepighetti I ran into the exact same problem at first, but after a while it got tsuck with only the REQUEST_DENIED status.
> Now, I tried to fetch data by manually making HTTP requests and found out that the status REQUEST_DENIED is not only send to the client when using wrong API keys, but also when Billing is not activated for the project. Here is what I got sent:
> 
> **You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable**
> 
> Maybe this helps some of you guys.

Thanks for the hint it was really a billing issue. I thought it is enough to have one billing account for the entire account but I had to link it to each project in the account to be able to use it.
