### ISSUE TITLE
Option to request only specific fields from API

### ISSUE THREAD

**Issue by mikah22** [bazrafkan/google_place#17]
Is there a way to request fetching only certain fields instead of everything that Google Places API has to offer. The reason why this is important is that Google has different pricing options based on what fields you are requesting. For example, Store open hours, Ratings are part of paid  API, and fields like name, GPS coordinates are part of Free API. Your assistance is highly appreciated.

**Comment by Charly6596** [comment]
Assuming you're talking about Place Details, you can see here there's a `fields` parameter
https://github.com/bazrafkan/google_place/blob/ad520e86d45f41852a38ec78a76d39856e0ba059/lib/src/details/details.dart#L39-L45
Its value should contain comma separated list of place data types to return as explained in [the google maps documentation](https://developers.google.com/maps/documentation/places/web-service/details#fields)
