### ISSUE TITLE
Error on example code

### ISSUE THREAD

**Issue by domizilver** [bazrafkan/google_place#2]
i got this error while running the code from example.

> 'package:google_place/google_place.dart': Failed assertion: line 65 pos 12: 'apiKEY != null': is not true.

i have my api key in 'api_key'.

**Comment by bazrafkan** [comment]
Hello,
This message show your apiKey is null.

Do you done these steps?

1. Create **.env** file in root of this example
2. Add your key for Google place API in this file (ex: API_KEY=XXXXXXXXXXX)??? **API_KEY no api_key**
3. Get packages from the command line: flutter pub get

**Comment by bazrafkan** [comment]
I think if you change **api_key** to **API_KEY** in **.env** file, it working

**Comment by domizilver** [comment]
yes i have my api key in "API_KEY". 
what do you mean by create .env file in root?

**Comment by bazrafkan** [comment]
you show create a file with name ** .env** in example directory, the write your key in this file like API_KEY=XXXXXXXXXXX

**Comment by domizilver** [comment]
you mean like this? i created key.env outside of lib folder same row as pubspec.yaml file

![Annotation 2020-05-08 044252](https://user-images.githubusercontent.com/61071761/81342796-69323f80-90e6-11ea-8b98-fae999e18a9e.png)

**Comment by bazrafkan** [comment]
your file name is "key.env", should be ".env", just change name of file to ".env"

**Comment by domizilver** [comment]
renamed to .env still no success :(

**Comment by bazrafkan** [comment]
Do you run `flutter pub get`?

**Comment by domizilver** [comment]
yes

**Comment by bazrafkan** [comment]
Now is working?

**Comment by domizilver** [comment]
still not working :(

**Comment by bazrafkan** [comment]
you can write directly your key in this line:
37:      String apiKey = DotEnv().env['API_KEY']; to String apiKey ="your-key";

**Comment by domizilver** [comment]
still not working.

![Annotation 2020-05-08 051845](https://user-images.githubusercontent.com/61071761/81345692-81f12400-90eb-11ea-8977-d1215538ba77.png)

 i tried my key on different google place api code and it works fine

**Comment by bazrafkan** [comment]
Now , what's the problem?

**Comment by domizilver** [comment]
same error

> 'package:google_place/google_place.dart': Failed assertion: line 65 pos 12: 'apiKEY != null': is not true.

**Comment by bazrafkan** [comment]
This error means you pass null to Google Place() for key, towmarrow I'll check again

**Comment by bazrafkan** [comment]
can I see your pubspec.yaml file in example directory?

**Comment by bazrafkan** [comment]
Thanks for your issue, I find the problem, if you get a new version and don 3 steps, should be working.

1. Create **.env** file in example directory
2. Add your Google Place API key in this file (ex: API_KEY=XXXXXXXXXXX)
3. Get packages from the command line: `flutter pub get`
