### ISSUE TITLE
remove flutter dependency

### ISSUE THREAD

**Issue by lukepighetti** [bazrafkan/google_place#21]
It looks like this package is pure Dart and does not depend on Flutter, but it is listed as a dependency. Any interest in removing this dependency?

https://github.com/bazrafkan/google_place/search?q=package%3Aflutter

**Comment by bazrafkan** [comment]
I remove flutter dependency in next version

**Comment by bazrafkan** [comment]
I already remove Flutter from dependency in 0.4.1 version
