### ISSUE TITLE
No Web support 

### ISSUE THREAD

**Issue by angwandi** [bazrafkan/google_place#23]
Please remove Web support from pub.dev

**Comment by jonmountjoy** [comment]
It would be easy to add web support if the author adds a proxyURL field, [like they do here](https://github.com/jaxnz/flutter_google_places_web).

BTW - you can get it to work on the web by changing all occurrences of something like this (here in `autocomplete.dart` )

```
class Autocomplete {
  static final _authority = 'maps.googleapis.com';
  static final _unencodedPath = 'maps/api/place/autocomplete/json';
```

to 

```
class Autocomplete {
  static final _authority = 'cors-anywhere.herokuapp.com';
  static final _unencodedPath = 'https://maps.googleapis.com/maps/api/place/autocomplete/json';
```

**Comment by bazrafkan** [comment]
Now is web supported in 0.4.2 version
