### ISSUE TITLE
JSON Output?

### ISSUE THREAD

**Issue by francescoprisco** [bazrafkan/google_place#28]
Hi, there are a possibility to get json output after select a prediction? I'm using autocomplete function. I'm trying to serialize AutocompletePrediction object without result. I neet json output to send it in http request

**Comment by bazrafkan** [comment]
I'll implement in the next version

**Comment by bazrafkan** [comment]
I already add in 0.4.3 version

**Comment by francescoprisco** [comment]
How i can do it? i've tried jsonEncode on AutocompletePrediction object but i can convert it into a json. i'vre tried to find a method too but i not found it

**Comment by bazrafkan** [comment]
You have to call ***getJson*** function like this:

`var googlePlace = GooglePlace("Your-Key");
var risult = await googlePlace.autocomplete.getJson("1600 Amphitheatre");`

then try to decode json (you can get help from this [document)](https://flutter.dev/docs/development/data-and-backend/json)

**Comment by francescoprisco** [comment]
can u implement output json on single AutocompletePrediction object? this will be very usefull
