### ISSUE TITLE
country specific search option not available

### ISSUE THREAD

**Issue by rvndsngwn** [bazrafkan/google_place#29]
I want search autocomplete work only a country specific not all over world!

**Comment by muneebahmad0600** [comment]
Same.. need feature asap if possible.

**Comment by rvndsngwn** [comment]
@muneebahmad0600 I'm now using this package `https://pub.dev/packages/flutter_google_places`.

**Comment by muneebahmad0600** [comment]
the documentation and example are both vague in that package. I tried using that package before this one. do u mind sharing the code for prediction listing? its multiple modes are kind of throwing me off a bit.

**Comment by rvndsngwn** [comment]
@muneebahmad0600  you can see full example with null safety of both packages: - https://gist.github.com/rvndsngwn/e2b11f8733e244e477925d7c186bd334

**Comment by muneebahmad0600** [comment]
Bro this the same code as the example which doesn't show how to restrict to a country. what I wanted to see was how you restrict the autoCompleteSearch() function to a country. if you are using the different library you mentioned above. please share that code.

**Comment by rvndsngwn** [comment]
```
  Prediction? p = await PlacesAutocomplete.show(
      context: context,
      apiKey: kGoogleApiKey,
      onError: onError,
      mode: _mode,
      language: "en",
      components: [Component(Component.country, "IN")],
    );
```
   In components you can specify witch country you allow like:-  `[Component(Component.country, "IN"),Component(Component.country, "AU"),Component(Component.country, "CA"),],`

**Comment by rvndsngwn** [comment]
you can restrict a country from your firebase.

**Comment by bazrafkan** [comment]
Already you can set country in this package that set in *components* .
for example set country like France:
`components: [Component("country","fr")]`
 
Example:

`var googlePlace = GooglePlace("Your-Key");
var risult = await googlePlace.autocomplete.get("1600 Amphitheatre", components: [Component("country","fr")]);`

**Comment by tiagoon** [comment]
> var googlePlace = GooglePlace("Your-Key"); var risult = await googlePlace.autocomplete.get("1600 Amphitheatre", components: [Component("country","fr")]);

Thanks! If you can put this information in the readme it will be very useful.

**Comment by abdulrehmank7** [comment]
Instead of using this plugin, I created a utility class for Google places auto complete : https://arkapp.medium.com/flutter-and-google-map-for-beginners-part-1-fdba4ab22148
