### ISSUE TITLE
Version 0.3.1 - Locationbias assertion throws error

### ISSUE THREAD

**Issue by erickharyono** [bazrafkan/google_place#3]
Unhandled Exception: Failed assertion: boolean expression must not be null
#0      new Locationbias (package:google_place/src/models/locationbias.dart:41:27)

**Comment by bazrafkan** [comment]
Hi
Can you show me ***Locationbias*** object that you used?
this error means you pass null to **ipbias**
Anyway, this object have four parameters , so you have to pass just one of this parameter, so you should pass null for others parameters.

locationbias — Prefer results in a specified area, by specifying either a radius plus lat/lng, or two lat/lng pairs representing the points of a rectangle.
[Link](https://developers.google.com/places/web-service/search)

for example:

- ipbias
```dart
  var locationbias = Locationbias(
    ipbias: true,
    point: null,
    circular: null,
    rectangular: null,
  );
```

- point
 ```dart
  var locationbias = Locationbias(
    ipbias: null,
    point: LatLon(18.0, 0.0),
    circular: null,
    rectangular: null,
  );
```

- circular
 ```dart
  var locationbias = Locationbias(
    ipbias: null,
    point: null,
    circular: Circular(100, LatLon(18.0, 0.0)),
    rectangular: null,
  );
```

- rectangular
 ```dart
  var locationbias = Locationbias(
    ipbias: null,
    point: null,
    circular: null,
    rectangular: Rectangular(LatLon(0.0, 0.0), LatLon(18.0, 0.0)),
  );
```

**Comment by LloydRBS** [comment]
Good Day

Is there any way to limit the auto complete location as explained in the google places documentation for Country or City

Thanks

**Comment by SlickSlime** [comment]
Hi @bazrafkan I am facing the same issue for the following LocationBias:

```

var locationbias = Locationbias(
      ipbias: null,
      point: null,
      circular: Circular(100, LatLon(18.0, 0.0)),
      rectangular: null,
    );

```

Seeing the source code it looks like instead of using only `if` statements there needs to be `if...else` statements so that we don't reach the line of code asserting values of invalid variables.

**Comment by bazrafkan** [comment]
I'll check, thanks.

**Comment by jgv115** [comment]
Hi @bazrafkan I am still facing the same issue on 0.4.3.

```
var locationbias = Locationbias(
      ipbias: null,
      point: null,
      circular: Circular(100, LatLon(18.0, 0.0)),
      rectangular: null,
    );
```


This code does not work because [this line](https://github.com/bazrafkan/google_place/blob/master/lib/src/models/locationbias.dart#L41) will fail at the `ipbias!` (since ipbias is null)

**Comment by bradrushworth** [comment]
Seriously, this breaks the entire library. This getFindPlace() API doesn't work because of this bug. Could you please fix it? Its a one line change!
