### ISSUE TITLE
Places api not working in flutter web

### ISSUE THREAD

**Issue by shubh420** [bazrafkan/google_place#32]
My below implementation is working fine in flutter iOS. But when running the same code in flutter web, its not working.

` 
 var googlePlace = GooglePlace("MY-API-KEY", proxyUrl: 'cors-anywhere.herokuapp.com');
 googlePlace.autocomplete .get(enteredAddress.value)
            .then((autocompleteResponse) {
          loading.value = false;
          predictionList.value = autocompleteResponse.predictions;
        }).onError((error, stackTrace) {
          CommonUIMethods.showSnackBar("Something went wrong. Please try again later.");
        }); 
`

in the web I am not getting any error. Execution does goes inside the `then` callback, But the autocompleteResponse object is null. Does the plugin works for flutter web or not?

**Comment by Desync-o-tron** [comment]
It does. Make sure your proxy is working.

**Comment by shubh420** [comment]
Sorry, My bad, My proxy url was not given permission. What should I use in place of "cors-anywhere.herokuapp.com", I dont know what can I do for prod.

**Comment by Desync-o-tron** [comment]
https://github.com/Rob--W/cors-anywhere
or when my pr gets merged, you can create your own proxy in python or w/e
