### ISSUE TITLE
FormatException while passing proxy url

### ISSUE THREAD

**Issue by shubh420** [bazrafkan/google_place#34]
Hi ,

I am passing `yacdn.org/proxy` as a proxy url to google_place. But I am getting below FormatException error when I run the app. 
  
```
FormatException: Invalid character (at character 10) yacdn.org/proxy
                                                              ^        
```

No other proxy url with subpath is working. How do I fix it?

**Comment by Desync-o-tron** [comment]
I made a pr to address this. Currently, you cannot have paths in the url.

**Comment by LucaDillenburg** [comment]
Hi @Desync-o-tron , any update on this?
