### ISSUE TITLE
Flutter Web - Can't google place autocomplete to work unless using proxy url.

### ISSUE THREAD

**Issue by DavidHCox** [bazrafkan/google_place#39]
**Has anybody got the google place working without using the proxy url?**

Right now we are using 'cors-anywhere.herokuapp.com' as the proxy url and works with limitations, but in the long run we just do not want to use one.

Is there something that I am not understanding about the web that requires a proxy url?

**Comment by RageshAntony** [comment]
> **Has anybody got the google place working without using the proxy url?**
> 
> Right now we are using 'cors-anywhere.herokuapp.com' as the proxy url and works with limitations, but in the long run we just do not want to use one.
> 
> Is there something that I am not understanding about the web that requires a proxy url?

https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code

**Comment by theRealBitcoinClub** [comment]
yes there is something you might have to investigate: https://duckduckgo.com/?q=what+is+a+CORS+requests

**Comment by Desync-o-tron** [comment]
yes. check my pr.
