### ISSUE TITLE
CORS in Web

### ISSUE THREAD

**Issue by RicardoRB** [bazrafkan/google_place#4]
Hi!

I saw this plugin was able on the web and trying it, it returns an error regarding CORS.

Any idea?

Access to XMLHttpRequest at 'https://maps.googleapis.com/maps/api/place/autocomplete/json?input=auerstras&key={MY_KEY}' from origin 'http://localhost:37277' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sarbogast** [comment]
Why is this closed? I still have the same issue. Shouldn't this plugin be able to use the [JS API](https://developers.google.com/maps/documentation/javascript/places) to get over this? In any case, right now, it doesn't work on the web
