### ISSUE TITLE
very wrong geometry details,

### ISSUE THREAD

**Issue by ralmarri12** [bazrafkan/google_place#6]
I had to use

```
Places.DetailsResponse detail = await googlePlace.details.get(placeId);
    double lat = detail.result.geometry.location.lat;
    double lng = detail.result.geometry.location.lng;
```

however, the information retrieved unfortunately were not correct. 
plus I really wish you append the (components part to allow using country)

**Update**
sorry I was wrong on details, it was correct. 

thank u

**Comment by bazrafkan** [comment]
thanks
