### ISSUE TITLE
Request with types return invalid reuest

### ISSUE THREAD

**Issue by asarkar1990** [bazrafkan/google_place#9]
var res = await googlePlace.autocomplete.get(query, types: 'cities');

**Comment by bazrafkan** [comment]
Hello,
I recommended to see this link for [Place type](https://developers.google.com/places/web-service/autocomplete?#place_types)

You have to set types to **types: '(cities)'**
```dart
var res = await googlePlace.autocomplete.get(query, types: '(cities)');
```
